<?php
/**
 * Plugin Name: WooCommerce Subscriptions Lite
 * Plugin URI: https://github.com/Automattic/woocommerce-subscriptions-lite
 * Description: Free subscriptions for WooCommerce, built on the WooCommerce subscriptions engine. Early development scaffold - not functional yet.
 * Author: Automattic
 * Author URI: https://automattic.com
 * Version: 0.0.1-dev
 * Requires PHP: 7.4
 * Requires at least: 6.9
 * WC requires at least: 10.0
 * License: GPLv3 or later
 * License URI: https://www.gnu.org/licenses/gpl-3.0.html
 * Text Domain: woocommerce-subscriptions-lite
 * Requires Plugins: woocommerce
 *
 * @package Automattic\WooCommerce\SubscriptionsLite
 */

declare( strict_types=1 );

namespace Automattic\WooCommerce\SubscriptionsLite;

defined( 'ABSPATH' ) || exit;

/*
 * Load order:
 *
 *   1. The Jetpack Autoloader bootstrap. Across every active plugin it loads the
 *      highest version of each shared class (this package's `src/` and the
 *      vendored engine), so exactly one copy resolves regardless of plugin load
 *      order. Generated by the automattic/jetpack-autoloader Composer plugin.
 *   2. On plugins_loaded priority 5, run the runtime guards and, if they pass,
 *      boot the feature modules.
 */

if ( ! file_exists( plugin_dir_path( __FILE__ ) . 'vendor/autoload_packages.php' ) ) {
	add_action(
		'admin_notices',
		static function (): void {
			echo '<div class="notice notice-error"><p>';
			echo esc_html__( 'WooCommerce Subscriptions Lite: dependencies are missing. Run composer install in the plugin directory.', 'woocommerce-subscriptions-lite' );
			echo '</p></div>';
		}
	);
	return;
}
require_once plugin_dir_path( __FILE__ ) . 'vendor/autoload_packages.php';

/**
 * Run the runtime guards and boot the feature modules.
 *
 * Stands down with an admin notice instead of fataling when a dependency is
 * missing: the Requires Plugins header is UI-only and does not guarantee the
 * dependency is present at runtime (wp-cli, partial deploys, and direct DB
 * edits all bypass it).
 *
 * Priority 5 runs after the version registries resolve at priority 0.
 */
add_action(
	'plugins_loaded',
	static function (): void {
		// Guard: WooCommerce must be active.
		if ( ! class_exists( 'WooCommerce' ) ) {
			add_action(
				'admin_notices',
				static function (): void {
					echo '<div class="notice notice-error"><p>';
					echo esc_html__( 'WooCommerce Subscriptions Lite requires WooCommerce to be active.', 'woocommerce-subscriptions-lite' );
					echo '</p></div>';
				}
			);
			return;
		}

		// Guard: the engine must be loaded. The Jetpack Autoloader resolves the
		// highest engine version across active plugins; if no copy is present,
		// stand down instead of fataling when the slice handlers call into it.
		//
		// TODO: once the engine exposes a version accessor, also compare the
		// resolved engine version against Lite's floor.
		if ( ! class_exists( \Automattic\WooCommerce\SubscriptionsEngine\Core\Entity\Contract::class ) ) {
			add_action(
				'admin_notices',
				static function (): void {
					echo '<div class="notice notice-error"><p>';
					echo esc_html__( 'WooCommerce Subscriptions Lite could not resolve the subscriptions engine.', 'woocommerce-subscriptions-lite' );
					echo '</p></div>';
				}
			);
			return;
		}

		Package::init();
	},
	5
);

/*
 * Flush rewrite rules on activation/deactivation so the My Account customer
 * portal endpoints resolve on first visit. The endpoint slugs are registered by
 * the Portal feature module (a later phase); flushing here is harmless before
 * those endpoints exist and avoids a stale-rewrite gap once they do.
 */
register_activation_hook(
	__FILE__,
	static function (): void {
		// TODO: register the portal endpoints before flushing once the Portal
		// module lands, so their rewrite rules are present at flush time.
		flush_rewrite_rules();
	}
);
register_deactivation_hook(
	__FILE__,
	static function (): void {
		flush_rewrite_rules();
	}
);
